version: '3.8'
services:
  backend:
    build:
      context: ./apps/nest
      dockerfile: Dockerfile
    container_name: nest_backend
    ports:
      - "3000:3000"
    volumes:
      - ./apps/nest:/app
      - /apps/node_modules
    environment:
      DATABASE_HOST: mysql_db
      DATABASE_PORT: 3306
      DATABASE_USER: root
      DATABASE_PASSWORD: Dulonx95*
      DATABASE_NAME: book_db
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    ports:
      - "3307:3306"           
    environment:
      MYSQL_ROOT_PASSWORD: Dulonx95*
      MYSQL_DATABASE: book_db
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: