version: '3.8'
services:
  backend:
    build:
      context: ./apps/nest
      dockerfile: Dockerfile
    container_name: nest_backend
    ports:
      - "3000:3000"
    volumes:
      - ./apps/nest:/app/nest
      - nest_node_modules:/apps/node_modules
    environment:
      DATABASE_HOST: ${DB_HOST}
      DATABASE_PORT: ${DB_PORT}
      DATABASE_USER: ${DB_USERNAME}
      DATABASE_PASSWORD: ${DB_PASSWORD}
      DATABASE_NAME: ${DB_NAME}
    depends_on:
      - db
  frontend:
    build:
      context: ./apps/client-react 
      dockerfile: Dockerfile
    container_name: react_frontend
    ports:
      - "5173:5173" 
    volumes:
      - ./apps/client-react:/app/client-react
      - react_node_modules:/app/node_modules
    environment:
      NODE_ENV: development 

  db:
    image: mysql
    container_name: mysql_db
    restart: always
    ports:
      - "3307:3306"           
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
  nest_node_modules:
  react_node_modules: