services:
  nest-api:
    build:
      context: ./apps/nest
      dockerfile: Dockerfile
    container_name: nest_backend
    env_file:
      - ./.env.docker
    ports:
      - "3000:3000"
    depends_on:
      mysql-db:
        condition: service_healthy
    volumes:
      # À retirer en prod si tu ne veux pas monter le code en live
      - ./apps/nest:/app

  client-react:
    build:
      context: ./apps/client-react
      dockerfile: Dockerfile
    container_name: react_frontend
    ports:
      - "5173:5173"
    volumes:
      - ./apps/client-react:/app
      - /app/node_modules
    stdin_open: true
    tty: true

  mysql-db:
    image: mysql:8
    container_name: mysql
    restart: always
    ports:
      - "3307:3306"
    env_file:
      - ./.env.docker
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql-data:
