export enum EnvironmentEnums {
  TWILIO_ACCOUNT_SID = 'TWILIO_ACCOUNT_SID',
  TWILIO_AUTH_TOKEN = 'TWILIO_AUTH_TOKEN',
  TWILIO_VERIFICATION_SERVICE_SID = 'TWILIO_VERIFICATION_SERVICE_SID',
  TWILIO_SENDER_PHONE_NUMBER = '15079441661',
}
