export enum ErrorsMessagesEnum {
  NOT_FOUND = 'NOT_FOUND',
  BAD_REQUEST = 'BAD_REQUEST',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  DATABASE_ERROR = 'DATABASE_ERROR',
  DUPLICATE_EMAIL = 'Cet email est déjà utilisé.',
  INVALID_PASSPORT = 'INVALID_PASSPORT',
  MISSING_REQUIRED_FIELD = 'MISSING_REQUIRED_FIELD',
  DATA_TOO_LONG = 'DATA_TOO_LONG',
  FOREIGN_KEY_CONSTRAINT = 'FOREIGN_KEY_CONSTRAINT',
  INVALID_DATA_TYPE = 'INVALID_DATA_TYPE',
}
