# Étape 1 : Build de l'application
FROM node:18 AS build

# Répertoire de travail pour la construction
WORKDIR /app

# Copie des fichiers package.json et package-lock.json
COPY package.json package-lock.json ./

# Installation des dépendances de production
RUN npm install --frozen-lockfile --production

# Copie du reste du code de l'application
COPY . .

# Construction de l'application Next.js (Génère le build de production)
RUN npm run build

# Étape 2 : Image de production (plus légère)
FROM node:18-alpine AS production

# Répertoire de travail pour la production
WORKDIR /app

# Copie uniquement les fichiers nécessaires du build précédent
COPY --from=build /app/.next ./.next
COPY --from=build /app/node_modules ./node_modules
COPY --from=build /app/public ./public

# Exposer le port 3000
EXPOSE 3000

# Définir la commande par défaut pour démarrer l'application
CMD ["npm", "run", "start"]
