# Étape 1 : Utiliser une image Node.js légère
FROM node:20 as development

# Étape de nettoyage avant la construction
RUN rm -rf /app/dist/*

# Définir le répertoire de travail dans le conteneur
WORKDIR /app

# Copier les fichiers package.json et package-lock.json pour optimiser le cache Docker
COPY package*.json ./

# Copier tout le code source
COPY . .

# Installer les dépendances nécessaires pour le développement
RUN npm install

ENV NODE_ENV developement


# Exposer le port utilisé par votre application NestJS (par défaut 3000)
EXPOSE 3000

# Commande pour démarrer l'application en mode développement
# npm run dev
CMD ["npm", "run", "start:dev"]
