# fly.toml app configuration file generated for nest-lively-rain-636 on 2025-03-17T12:52:57+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'nest-lively-rain-636'
primary_region = 'cdg'

[build]
  dockerfile = "Dockerfile.prod"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
